ARG BASEIMG=docker.io/ubuntu:22.04
FROM $BASEIMG

MAINTAINER Andreas Fink <andreas.fink@cscs.ch>

ARG SPACK_REPO=https://github.com/finkandreas/spack
ARG SPACK_VER=v0.19.0
ENV SPACK_ROOT=/opt/spack

RUN apt-get update \
  && env DEBIAN_FRONTEND=noninteractive TZ=Europe/Zurich \
  apt-get -yqq install --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    file \
    clang-15 \
    g++ \
    gcc \
    gfortran \
    git \
    gnupg2 \
    iproute2 \
    lmod \
    locales \
    lua-posix \
    make \
    patch \
    python-is-python3 \
    python3 \
    python3-boto3 \
    python3-pip \
    python3-setuptools \
    tcl \
    unzip \
    vim \
    less \
  && locale-gen en_US.UTF-8 \
  && rm -Rf /var/lib/apt/lists/*

RUN mkdir -p $SPACK_ROOT \
  && git clone -b ${SPACK_VER} ${SPACK_REPO} ${SPACK_ROOT} \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/docker-shell \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/interactive-shell \
  && ln -s $SPACK_ROOT/share/spack/docker/entrypoint.bash /usr/local/bin/spack-env \
  && echo '[[ -v MODULEPATH ]] && unset MODULEPATH' >> $SPACK_ROOT/share/spack/setup-env.sh

ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN mkdir -p /root/.spack \
 && cp $SPACK_ROOT/share/spack/docker/modules.yaml /root/.spack/modules.yaml \
 && rm -rf /root/*.* /run/nologin $SPACK_ROOT/.git

WORKDIR /root
SHELL ["docker-shell"]

RUN spack mirror add --scope site s3_cscs_buildcache https://object.cscs.ch/v1/AUTH_21e698ff1238438fabc72e5cf9d59165/anfink_spack_cache \
  && spack mirror set-url --scope site --push --s3-endpoint-url https://object.cscs.ch s3_cscs_buildcache s3://anfink_spack_cache \
  && spack buildcache keys -it \
  && spack spec hdf5+mpi

COPY bin/* /usr/local/bin
COPY spack_env.yaml /opt/spack_env.yaml.template

# Re-export CUDA_VERSION, because nvidia/sarus think that this is a precious variable that needs protection and must be erased
ENV ALSO_CUDA_VERSION=$CUDA_VERSION

ENTRYPOINT ["/bin/bash", "/opt/spack/share/spack/docker/entrypoint.bash"]
CMD ["interactive-shell"]
